---
helm_repos:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: cilium
    url: https://helm.cilium.io/
